### PR TITLE
interop: add tests

### PR DESCRIPTION
**Pull request by mparis**

### CODE REVIEW

**Comment by mparis** [comment]
Before accepting this patch, I would like to know how you format the source code to keep the style.

**Comment by gpolitis** [comment]
Hello @mparis, I just merged your PR, thanks! Do you have any scripts defined to run the tests? If so, could you please make a PR for them as well when you find some time? Thanks!

**Comment by mparis** [comment]
No, I just run "node test/sdp_interop.js".
Before you have to run "npm install" in order to get the test libs.

About the source, do you use some kind of formater to keep the style?

**Comment by gpolitis** [comment]
Thanks @mparis! I've just updated the .jshintignore file so that jshint ignores test/sdp_interop.js. It's much more readable to have the SDP lines not broken down. In general, the formatting rules are described in .jhintrc and there's a pre-commit hook setup that checks code quality.

**Pull request merged**
